
before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    binary: hc
    main: main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X github.com/roseboy/httpcase/cmd.GitVersion={{.Version}} -X github.com/roseboy/httpcase/cmd.GitCommit={{.Commit}} -X github.com/roseboy/httpcase/cmd.BuildDate={{ .CommitDate }} -X github.com/roseboy/httpcase/cmd.BuiltBy=Mr.K
archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - tap:
      owner: roseboy
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/roseboy/httpcase
    description: 接口自动化测试工具
    license: MulanPSL2
    test: |
      system "#{bin}/hc version"
    install: |-
      bin.install "hc"